import React from 'react'
import Script from 'next/script'

const page = () => {
  return (
    <div>
      <Script>
        {"alert('welcome to this page');"}
      </Script>
      i am contact
    </div>
  )
}

export default page
export const metadata = {
  title: "just learning contact",
  description: "Generated by crldjkjfkjdkjfkeate next to learn this nextj app",
};
