import React from 'react'

const page = () => {
  return (
    <div>
      i am about
    </div>
  )
}

export default page
export const metadata = {
  title: "just learning about",
  description: "Generated by jfidjfhdkfjkdjcreate next to learn this nextj app",
};
